export {default as DictionaryForm} from './DictionaryForm';
export {default as NegativeForm} from './NegativeForm';
export {default as PastForm} from './PastForm';
export {default as PoliteForm} from './PoliteForm';
export {default as TeForm} from './TeForm';
export {default as FormBox} from './FormBox';
export {default as negativeConfig} from './TypeConfigs/negativeConfig';
export {default as dictionaryConfig} from './TypeConfigs/dictionaryConfig';
export {default as politeConfig} from './TypeConfigs/politeConfig';
export {default as negativePoliteConfig} from './TypeConfigs/negativePoliteConfig';
export {default as pastConfig} from './TypeConfigs/pastConfig'